version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: rustic-debug-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-readonly:
    image: redis:7-alpine
    container_name: rustic-debug-redis-readonly
    command: redis-server --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6380:6379"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data: